[server]
headless = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false

[theme]
primaryColor = "#FEC925"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E2E"
textColor = "#E0E0E0"
font = "sans serif"
